# Generated by Django 5.0.4 on 2024-05-02 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo_date_tobe_finishedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_toBe_finishedBy',
            field=models.DateField(default=datetime.datetime(2024, 5, 2, 12, 12, 41, 813428, tzinfo=datetime.timezone.utc), verbose_name='Date to be finished by'),
        ),
    ]
